Load necessary libraries.

In [10]:
import numpy as np

Initialize matrices

(i) Point wise matrix multiplication to get C

In [11]:
A = np.array([[3,9,5,1],[4,25,4,3],[63,13,23,9],[6,32,77,0],[12,8,6,1]])
B = np.array([[0,1,0,1],[0,1,1,0],[0,0,0,1],[1,1,0,1],[0,1,0,0]])
print("A = \n",A)
print("B = \n",B)

A = 
 [[ 3  9  5  1]
 [ 4 25  4  3]
 [63 13 23  9]
 [ 6 32 77  0]
 [12  8  6  1]]
B = 
 [[0 1 0 1]
 [0 1 1 0]
 [0 0 0 1]
 [1 1 0 1]
 [0 1 0 0]]


In [12]:
C = np.multiply(A,B)
print("C = ", C)

C =  [[ 0  9  0  1]
 [ 0 25  4  0]
 [ 0  0  0  9]
 [ 6 32  0  0]
 [ 0  8  0  0]]


(ii) Inner product of $2^{nd} \&$ $3^{rd}$ rows of C.

In [13]:
ip = np.dot(C[1,:], C[2,:])
print("Inner product of 2nd and 3rd row of C is ", ip)

Inner product of 2nd and 3rd row of C is  0


(iii) Maximum and minimum of C

In [14]:
max = np.amax(C)
maxIndices = np.where(C == max)
print('Maximum value of C is ', max, ' at index (', maxIndices[0][0], ',', maxIndices[1][0], ')')

Maximum value of C is  32  at index ( 3 , 1 )


In [15]:
min = np.amin(C)
minIndices = np.where(C == min)
print('Maximum value of C is ', min, ' at index (', minIndices[0][0], ',', minIndices[1][0], ')')

Maximum value of C is  0  at index ( 0 , 0 )
